In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
s = pd.Series(data=[1, "2", [3], {"4"}],
              index=[3, "2", True, [0]])
s

3         1
2         2
True    [3]
[0]     {4}
dtype: object

In [9]:
s[True]

[3]

In [10]:
s[1:3]

2         2
True    [3]
dtype: object

In [11]:
df1 = pd.DataFrame([[1,2], ["1", "2"], [[],[]]])
df1

    0   1
0   1   2
1   1   2
2  []  []

In [16]:
df2 = pd.DataFrame([[1,2], ["1", "2"], [3,4]], columns=['ноль','один'], index=['один','два','три'])
df2

     ноль один
один    1    2
два     1    2
три     3    4

In [2]:
url = "data.csv"

In [3]:
df = pd.read_csv(url)
df.head()

   user_id   age country  purchases  revenue
0        1  25.0      FR          7      749
1        2  24.0      RU          5     1115
2        3  52.0      FR          7      399
3        4  31.0      RU          6      654
4        5   NaN      DE          6     1296

Информация о столбцих и типах

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    41 non-null     int64
 1   age        39 non-null     float64
 2   country    41 non-null     object
 3   purchases  41 non-null     int64
 4   revenue    41 non-null     int64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.7+ KB

Базовые описвтельные статистики

In [19]:
df.describe()

         user_id         age  purchases      revenue
count  41.000000   39.000000  41.000000    41.000000
mean   20.243902   36.512821   4.829268   820.048780
std    11.659289   18.304259   2.710189   613.127269
min     1.000000    5.000000  -1.000000     0.000000
25%    10.000000   24.000000   3.000000   432.000000
50%    20.000000   33.000000   5.000000   693.000000
75%    30.000000   45.500000   7.000000  1115.000000
max    40.000000  120.000000  11.000000  2475.000000

Проверка пропусков в df в каждом столбце

In [21]:
df.isnull().sum()

user_id      0
age          2
country      0
purchases    0
revenue      0
dtype: int64

Типы данных

In [23]:
df.dtypes

user_id        int64
age          float64
country       object
purchases      int64
revenue        int64
dtype: object

Количество дублирующих строк

In [27]:
df.duplicated().sum()

np.int64(1)

Доля пропусков в каждом столбце

In [28]:
df.isna().mean()

user_id      0.00000
age          0.04878
country      0.00000
purchases    0.00000
revenue      0.00000
dtype: float64

Сами дублирующиеся строки

In [30]:
df[df.duplicated(keep=False)]

    user_id   age country  purchases  revenue
9        10  24.0      RU          7      511
40       10  24.0      RU          7      511

In [5]:
df.dtypes

user_id        int64
age          float64
country       object
purchases      int64
revenue        int64
dtype: object

Провека качетсва

In [16]:
problems = {}

problems["null_user"] = df["user_id"].isna().sum()
problems["null_age"] = df["age"].isna().sum()
problems["null_country"] = df["country"].isna().sum()
problems["invalid_age"] = ((df["age"] < 0) | (df["age"] > 110)).sum()
problems["invalid_revenue"] = ((df["revenue"] < 0) | (df["revenue"] > 100000)).sum()
problems["invalid_wastes"] = ((df["revenue"] <= 0) & (df["purchases"] > 0)).sum()
problems["invalid_purchases"] = (df["purchases"] < 0).sum()

report = pd.Series(problems, name = "n_bad_rows")
print(report)

null_user            0
null_age             2
null_country         0
invalid_age          1
invalid_revenue      0
invalid_wastes       1
invalid_purchases    1
Name: n_bad_rows, dtype: int64

In [13]:
df

    user_id    age country  purchases  revenue
0         1   25.0      FR          7      749
1         2   24.0      RU          5     1115
2         3   52.0      FR          7      399
3         4   31.0      RU          6      654
4         5    NaN      DE          6     1296
5         6  120.0      FR         -1      785
6         7   46.0      RU          0        0
7         8   28.0      CN          2      456
8         9   39.0      US          4      980
9        10   24.0      RU          7      511
10       11   24.0      US          4        0
11       12   20.0      CN          7     1652
12       13    NaN      US          9      630
13       14   36.0      DE          9     2358
14       15   57.0      FR          7      693
15       16   22.0      FR          3      183
16       17   32.0      FR          6     1608
17       18   24.0      RU          0        0
18       19   47.0      RU          3      432
19       20   31.0      RU          2      442
20       21    5.0      RU          8     1488
21       22   33.0      FR          6      546
22       23   42.0      US          4      904
23       24   32.0      DE         11     2475
24       25   21.0      RU          5      650
25       26   35.0      US          5      330
26       27   54.0      RU          6     1302
27       28   43.0      US          3      828
28       29   47.0      FR          6     1440
29       30   52.0      DE          6      702
30       31   55.0      FR          1      142
31       32   26.0      RU          6     1080
32       33   23.0      US          5      445
33       34   28.0      FR          0        0
34       35   45.0      FR          2      404
35       36   51.0      US          3      342
36       37   18.0      DE          4     1104
37       38   35.0      DE          3      738
38       39   39.0      FR          7     1162
39       40   34.0      RU          7     2086
40       10   24.0      RU          7      511

В данных присутствуют следующие проблемы качеста:
1 Найдено 2 случая с nan в значениии возраста
2 Найден 1 случай с нереалистичным возрастом
3 Найден 1 случай с несоответствием заработка и покупок
4 Найдено 1 некорректное значение покупок

Подсчет частот

In [17]:
df["country"].value_counts()

country
RU    13
FR    12
US     8
DE     6
CN     2
Name: count, dtype: int64

In [18]:
df["age"].value_counts()

age
24.0     5
52.0     2
31.0     2
39.0     2
28.0     2
35.0     2
47.0     2
32.0     2
20.0     1
25.0     1
46.0     1
120.0    1
22.0     1
57.0     1
36.0     1
5.0      1
33.0     1
42.0     1
21.0     1
54.0     1
43.0     1
55.0     1
26.0     1
23.0     1
45.0     1
51.0     1
18.0     1
34.0     1
Name: count, dtype: int64

Групировка с агрегатами

In [20]:
df.groupby("country")["age"].agg(['mean','sum','median'])

              mean    sum  median
country
CN       24.000000   48.0    24.0
DE       34.600000  173.0    35.0
FR       46.250000  555.0    42.0
RU       30.076923  391.0    26.0
US       36.714286  257.0    39.0

In [21]:
df.groupby(["country","age"])["revenue"].mean()

country  age
CN       20.0     1652.00
         28.0      456.00
DE       18.0     1104.00
         32.0     2475.00
         35.0      738.00
         36.0     2358.00
         52.0      702.00
FR       22.0      183.00
         25.0      749.00
         28.0        0.00
         32.0     1608.00
         33.0      546.00
         39.0     1162.00
         45.0      404.00
         47.0     1440.00
         52.0      399.00
         55.0      142.00
         57.0      693.00
         120.0     785.00
RU       5.0      1488.00
         21.0      650.00
         24.0      534.25
         26.0     1080.00
         31.0      548.00
         34.0     2086.00
         46.0        0.00
         47.0      432.00
         54.0     1302.00
US       23.0      445.00
         24.0        0.00
         35.0      330.00
         39.0      980.00
         42.0      904.00
         43.0      828.00
         51.0      342.00
Name: revenue, dtype: float64

Коридоры

In [31]:
bins = [0, 18, 30, 45, 60, 100]
labels = ['0–18', '19–30', '31–45', '46–60', '60+']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

df['age_group'].value_counts()

age_group
31–45    14
19–30    13
46–60     9
0–18      2
60+       0
Name: count, dtype: int64

In [ ]:
bins = [0, 100, 200, 300, 400, 500, 1000]
labels = ['0-100', '101-200', '201-300', '301-400', '401-500','501+']
df['revenue_group'] = pd.cut(df['revenue'], bins=bins, labels=labels)

df['revenue_group']

revenue_group
501+       14
401-500     5
301-400     3
101-200     2
0-100       0
201-300     0
Name: count, dtype: int64

В данном датафрейме преобладают следующие группы возрастов: "31-45"(14 чел) и "19-30"(13 чел)
Также в данном датафрейме пробладают люди с достатком 501+